# Этап build
FROM python:3.12-slim AS builder
WORKDIR /app
COPY . .

# Этап копирования результатов build И запуск
FROM python:3.12-slim
WORKDIR /app
RUN pip install uvicorn mysql-connector-python fastapi
COPY --from=builder /app/main.py /app/main.py
EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
